In [2]:
import pandas as pd

In [6]:
df = pd.read_pickle('./objects/causal_dataset.pkl')

In [7]:
df

,age,aliq_at,aliq_mat,ami_126d,at_be,at_gr1,at_me,at_turnover,be_gr1a,be_me,...,taccruals_ni,tangibility,tax_gr1a,turnover_126d,turnover_var_126d,z_score,zero_trades_126d,zero_trades_21d,zero_trades_252d,target
0,132,0.985818,0.059472,0.000026,1.260918,0.651395,0.042021,1.028183,0.310450,0.033325,...,0.932668,0.287709,0.018174,0.003022,0.336775,43.032362,0.004157,0.005002,0.003226,1
23522,600,0.610528,0.069305,0.000105,2.318300,-0.088342,0.149204,0.845524,-0.035351,0.064359,...,-0.078292,0.698118,-0.013003,0.002484,0.472298,10.113916,0.004944,0.006133,0.004822,1
75824,325,NaN,NaN,0.004628,11.225380,0.119811,4.214064,0.086138,0.003968,0.375405,...,NaN,NaN,0.001342,0.003168,0.729098,NaN,0.003974,0.004473,0.004011,1
76014,60,0.616255,0.219590,0.000887,2.971011,0.093083,0.441731,1.506417,0.083045,0.148680,...,-0.235251,0.523392,0.002257,0.003886,0.509687,5.348204,0.003278,0.004529,0.003185,1
129371,72,0.613501,0.109210,0.001278,2.574726,0.012174,0.169081,1.197614,0.235894,0.065669,...,0.862540,0.372946,0.029722,0.006013,1.056336,8.349836,0.001912,0.002674,0.002260,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77686,654,0.348917,0.075573,0.000042,4.048223,0.026266,0.219966,0.381231,0.051937,0.054336,...,-0.011212,0.313022,-0.012389,0.003985,0.431750,5.694486,0.007268,0.005775,0.007261,1
110708,875,0.541670,0.469106,0.000079,3.390920,0.101955,2.579604,0.224324,0.020290,0.760739,...,-4.384845,0.597077,0.000223,0.012001,0.473572,0.648063,0.002548,0.001582,0.002992,1
77970,683,0.412350,0.106346,0.000052,23.971774,-0.034589,0.334292,1.221020,-0.062910,0.013945,...,-5.644295,0.606730,-0.009924,0.011881,0.590305,3.961255,0.002585,0.001735,0.003006,-1
9565,527,0.566360,0.404144,0.000205,5.153496,0.190384,1.926307,2.614588,-0.023169,0.373786,...,-1.650558,0.483529,-0.006986,0.013285,0.537003,3.973304,0.002241,0.002721,0.002129,1
131463,936,0.502752,0.448166,0.000064,2.224959,0.033296,1.989022,0.229889,-0.000261,0.893959,...,-2.701708,0.587483,0.000052,0.007469,0.391692,1.081265,0.004487,0.003086,0.004744,1

In [10]:
df.columns.to_list()

['age',
 'aliq_at',
 'aliq_mat',
 'ami_126d',
 'at_be',
 'at_gr1',
 'at_me',
 'at_turnover',
 'be_gr1a',
 'be_me',
 'beta_60m',
 'beta_dimson_21d',
 'betabab_1260d',
 'betadown_252d',
 'bev_mev',
 'bidaskhl_21d',
 'capex_abn',
 'capx_gr1',
 'capx_gr2',
 'capx_gr3',
 'cash_at',
 'chcsho_12m',
 'coa_gr1a',
 'col_gr1a',
 'cop_at',
 'cop_atl1',
 'corr_1260d',
 'coskew_21d',
 'cowc_gr1a',
 'dbnetis_at',
 'debt_gr3',
 'debt_me',
 'dgp_dsale',
 'div12m_me',
 'dolvol_126d',
 'dolvol_var_126d',
 'dsale_dinv',
 'dsale_drec',
 'dsale_dsga',
 'earnings_variability',
 'ebit_bev',
 'ebit_sale',
 'ebitda_mev',
 'emp_gr1',
 'eq_dur',
 'eqnetis_at',
 'eqnpo_12m',
 'eqnpo_me',
 'eqpo_me',
 'f_score',
 'fcf_me',
 'fnl_gr1a',
 'gp_at',
 'gp_atl1',
 'intrinsic_value',
 'inv_gr1',
 'inv_gr1a',
 'iskew_capm_21d',
 'iskew_ff3_21d',
 'iskew_hxz4_21d',
 'ivol_capm_21d',
 'ivol_capm_252d',
 'ivol_ff3_21d',
 'ivol_hxz4_21d',
 'kz_index',
 'lnoa_gr1a',
 'lti_gr1a',
 'market_equity',
 'mispricing_mgmt',
 'mispricing_perf',
 'ncoa_gr1a',
 'ncol_gr1a',
 'netdebt_me',
 'netis_at',
 'nfna_gr1a',
 'ni_ar1',
 'ni_be',
 'ni_inc8q',
 'ni_ivol',
 'ni_me',
 'niq_at',
 'niq_at_chg1',
 'niq_be',
 'niq_be_chg1',
 'niq_su',
 'nncoa_gr1a',
 'noa_at',
 'noa_gr1a',
 'o_score',
 'oaccruals_at',
 'oaccruals_ni',
 'ocf_at',
 'ocf_at_chg1',
 'ocf_me',
 'ocfq_saleq_std',
 'op_at',
 'op_atl1',
 'ope_be',
 'ope_bel1',
 'opex_at',
 'pi_nix',
 'ppeinv_gr1a',
 'prc',
 'prc_highprc_252d',
 'qmj',
 'qmj_growth',
 'qmj_prof',
 'qmj_safety',
 'rd_me',
 'rd_sale',
 'rd5_at',
 'resff3_12_1',
 'resff3_6_1',
 'ret_1_0',
 'ret_12_1',
 'ret_12_7',
 'ret_3_1',
 'ret_6_1',
 'ret_60_12',
 'ret_9_1',
 'rmax1_21d',
 'rmax5_21d',
 'rmax5_rvol_21d',
 'rskew_21d',
 'rvol_21d',
 'sale_bev',
 'sale_emp_gr1',
 'sale_gr1',
 'sale_gr3',
 'sale_me',
 'saleq_gr1',
 'saleq_su',
 'seas_1_1an',
 'seas_1_1na',
 'seas_2_5an',
 'seas_2_5na',
 'sti_gr1a',
 'taccruals_at',
 'taccruals_ni',
 'tangibility',
 'tax_gr1a',
 'turnover_126d',
 'turnover_var_126d',
 'z_score',
 'zero_trades_126d',
 'zero_trades_21d',
 'zero_trades_252d',
 'target']

In [9]:
df['t1']

KeyError: 't1'

In [11]:
df = pd.read_pickle('./objects/X_dataset.pkl')

In [15]:
df.columns.to_list()

['age',
 'aliq_at',
 'aliq_mat',
 'ami_126d',
 'at_be',
 'at_gr1',
 'at_me',
 'at_turnover',
 'be_gr1a',
 'be_me',
 'beta_60m',
 'beta_dimson_21d',
 'betabab_1260d',
 'betadown_252d',
 'bev_mev',
 'bidaskhl_21d',
 'capex_abn',
 'capx_gr1',
 'capx_gr2',
 'capx_gr3',
 'cash_at',
 'chcsho_12m',
 'coa_gr1a',
 'col_gr1a',
 'cop_at',
 'cop_atl1',
 'corr_1260d',
 'coskew_21d',
 'cowc_gr1a',
 'dbnetis_at',
 'debt_gr3',
 'debt_me',
 'dgp_dsale',
 'div12m_me',
 'dolvol_126d',
 'dolvol_var_126d',
 'dsale_dinv',
 'dsale_drec',
 'dsale_dsga',
 'earnings_variability',
 'ebit_bev',
 'ebit_sale',
 'ebitda_mev',
 'emp_gr1',
 'eq_dur',
 'eqnetis_at',
 'eqnpo_12m',
 'eqnpo_me',
 'eqpo_me',
 'f_score',
 'fcf_me',
 'fnl_gr1a',
 'gp_at',
 'gp_atl1',
 'intrinsic_value',
 'inv_gr1',
 'inv_gr1a',
 'iskew_capm_21d',
 'iskew_ff3_21d',
 'iskew_hxz4_21d',
 'ivol_capm_21d',
 'ivol_capm_252d',
 'ivol_ff3_21d',
 'ivol_hxz4_21d',
 'kz_index',
 'lnoa_gr1a',
 'lti_gr1a',
 'market_equity',
 'mispricing_mgmt',
 'mispricing_perf',
 'ncoa_gr1a',
 'ncol_gr1a',
 'netdebt_me',
 'netis_at',
 'nfna_gr1a',
 'ni_ar1',
 'ni_be',
 'ni_inc8q',
 'ni_ivol',
 'ni_me',
 'niq_at',
 'niq_at_chg1',
 'niq_be',
 'niq_be_chg1',
 'niq_su',
 'nncoa_gr1a',
 'noa_at',
 'noa_gr1a',
 'o_score',
 'oaccruals_at',
 'oaccruals_ni',
 'ocf_at',
 'ocf_at_chg1',
 'ocf_me',
 'ocfq_saleq_std',
 'op_at',
 'op_atl1',
 'ope_be',
 'ope_bel1',
 'opex_at',
 'pi_nix',
 'ppeinv_gr1a',
 'prc',
 'prc_highprc_252d',
 'qmj',
 'qmj_growth',
 'qmj_prof',
 'qmj_safety',
 'rd_me',
 'rd_sale',
 'rd5_at',
 'resff3_12_1',
 'resff3_6_1',
 'ret_1_0',
 'ret_12_1',
 'ret_12_7',
 'ret_3_1',
 'ret_6_1',
 'ret_60_12',
 'ret_9_1',
 'rmax1_21d',
 'rmax5_21d',
 'rmax5_rvol_21d',
 'rskew_21d',
 'rvol_21d',
 'sale_bev',
 'sale_emp_gr1',
 'sale_gr1',
 'sale_gr3',
 'sale_me',
 'saleq_gr1',
 'saleq_su',
 'seas_1_1an',
 'seas_1_1na',
 'seas_2_5an',
 'seas_2_5na',
 'sti_gr1a',
 'taccruals_at',
 'taccruals_ni',
 'tangibility',
 'tax_gr1a',
 'turnover_126d',
 'turnover_var_126d',
 'z_score',
 'zero_trades_126d',
 'zero_trades_21d',
 'zero_trades_252d',
 'log_diff',
 'frac_diff',
 'sadf']

In [13]:
df['t1']

KeyError: 't1'