In [1]:
import numpy as np
import pandas as pd

import pickle as pkl

In [2]:
# load objects/t1.pkl
with open('../objects/t1.pkl', 'rb') as f:
    t1 = pkl.load(f)

In [3]:
t1

datetime
2000-02-01   2000-02-29
2000-03-01   2000-03-31
2000-04-03   2000-04-28
2000-05-01   2000-05-31
2000-06-01   2000-06-30
                ...
2023-09-01   2023-09-29
2023-10-02   2023-10-31
2023-11-01   2023-11-30
2023-12-01   2023-12-29
2024-01-01   2024-01-31
Length: 288, dtype: datetime64[ns]

In [4]:
# Now let's check if the index is correctly set when reading the saved file
path = '../stocks_data/AAPL.csv'
df = pd.read_csv(path, index_col='datetime', parse_dates=True)

In [5]:
df

,date,ret_eom,permno,shrcd,exchcd,mspread,year,month,size_port,rf,...,target,total_return,adj_price,log_price,log_diff,weight_attr,prediction,probability,frac_diff,sadf
datetime,,,,,,,,,,,,,,,,,,,,,
2000-01-31,20000131,20000131,14593,11,3,0.016324,2000,1,B,0.0041,...,1,0.000000,102.812500,4.632907,0.000000,0.005019,-1.0,0.964103,0.000000,0.000000
2000-02-29,20000229,20000229,14593,11,3,0.013985,2000,2,B,0.0043,...,1,0.009119,103.750000,4.641984,0.009077,0.100519,-1.0,0.461999,0.000000,0.000000
2000-03-31,20000331,20000331,14593,11,3,0.016546,2000,3,B,0.0047,...,1,0.104819,114.625000,4.741666,0.099682,0.180142,-1.0,0.304472,0.000000,0.000000
2000-04-28,20000428,20000430,14593,11,3,0.027399,2000,4,B,0.0046,...,-1,0.184842,135.812499,4.911275,0.169609,0.091116,-1.0,0.576389,0.000000,0.000000
2000-05-31,20000531,20000531,14593,11,3,0.013961,2000,5,B,0.0050,...,-1,-0.086516,124.062499,4.820785,-0.090490,0.327922,-1.0,0.258690,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-31,20230831,20230831,14593,11,3,0.003065,2023,8,B,0.0045,...,-1,0.012785,25819.197721,10.158874,0.012704,0.046954,1.0,0.969946,1.580522,-0.796085
2023-09-29,20230929,20230930,14593,11,3,0.005090,2023,9,B,0.0043,...,-1,-0.042454,24723.080836,10.115493,-0.043381,0.092978,1.0,0.896877,1.512328,-1.345121
2023-10-31,20231031,20231031,14593,11,3,0.005148,2023,10,B,0.0047,...,-1,-0.088678,22530.680427,10.022633,-0.092859,0.007270,1.0,0.669793,1.431594,-1.630790
2023-11-30,20231130,20231130,14593,11,3,0.002650,2023,11,B,0.0044,...,1,-0.002570,22472.777548,10.020060,-0.002573,0.109320,-1.0,0.396794,1.476798,-1.628027
2023-12-29,20231229,20231231,14593,11,3,0.002511,2023,12,B,0.0043,...,1,0.113720,25028.385489,10.127766,0.107706,0.009283,1.0,0.626355,1.594457,-1.846643